galaxyproject/tools-devteam

- tools/bwa/bwa-mem.xml
Some fixes derived by https://bitbucket.org/crs4/orione-tools/src/HEAD/custom/bwa_mem/bwa_mem.xml .
> Fixes for bwa-mem

- tools/bowtie2/bowtie2_wrapper.xml
> Fix bugs and typos

- tools/weblogo3/rgWebLogo3.xml
- tools/weblogo3/tool_dependencies.xml
fix for: https://github.com/galaxyproject/tools-devteam/issues/65
> fix dependencies for weblogo

- packages/package_velvet_1_2_10/tool_dependencies.xml
- tools/velvet/.shed.yml
- tools/velvet/macros.xml
- tools/velvet/tool_dependencies.xml
- tools/velvet/velvetg.xml
- tools/velvet/velvetg_wrapper.py
- tools/velvet/velveth.xml
- tools/velvet/velveth_wrapper.py
Imported the commented out sr_assembly tool velvet, added a package for it.
*it would be nice* if Galaxy had configurable package installs as part of the future. It's, admittedly, a bit of a corner case, but velvet has the setting `MAXKMERLENGTH` which we need set higher than the default. Instead I just re-built the tool and copied the binaries manually into the install dir.
> Velvet (+package) from galaxy

- tools/add_value/fixedValueColumn.xml
- tools/change_case/changeCase.xml
- tools/condense_characters/condense_characters.xml
- tools/convert_characters/convert_characters.xml
- tools/fasta_compute_length/fasta_compute_length.xml
- tools/remove_beginning/remove_beginning.xml
- tools/show_beginning/headWrapper.xml
- tools/show_tail/tailWrapper.xml
See discussion on IUC mailing list, CC @davebx
> Make tool version explicit (Tool Shed would assume 1.0.0)

- tool_collections/samtools/bam_to_sam/bam_to_sam.xml
- tool_collections/samtools/bam_to_sam/macros.xml
- tool_collections/samtools/macros.xml
- tool_collections/samtools/sam_to_bam/macros.xml
- tool_collections/samtools/sam_to_bam/sam_to_bam.xml
- tool_collections/samtools/samtools_bedcov/macros.xml
- tool_collections/samtools/samtools_bedcov/samtools_bedcov.xml
- tool_collections/samtools/samtools_calmd/macros.xml
- tool_collections/samtools/samtools_calmd/samtools_calmd.xml
- tool_collections/samtools/samtools_flagstat/macros.xml
- tool_collections/samtools/samtools_flagstat/samtools_flagstat.xml
- tool_collections/samtools/samtools_idxstats/macros.xml
- tool_collections/samtools/samtools_idxstats/samtools_idxstats.xml
- tool_collections/samtools/samtools_mpileup/macros.xml
- tool_collections/samtools/samtools_mpileup/samtools_mpileup.xml
- tool_collections/samtools/samtools_phase/macros.xml
- tool_collections/samtools/samtools_phase/samtools_phase.xml
- tool_collections/samtools/samtools_reheader/macros.xml
- tool_collections/samtools/samtools_reheader/samtools_reheader.xml
- tool_collections/samtools/samtools_rmdup/macros.xml
- tool_collections/samtools/samtools_rmdup/samtools_rmdup.xml
- tool_collections/samtools/samtools_slice_bam/macros.xml
- tool_collections/samtools/samtools_slice_bam/samtools_slice_bam.xml
- tool_collections/samtools/samtools_sort/macros.xml
- tool_collections/samtools/samtools_sort/samtools_sort.xml
- tool_collections/samtools/samtools_split/macros.xml
- tool_collections/samtools/samtools_split/samtools_split.xml
- tool_collections/samtools/samtools_stats/macros.xml
- tool_collections/samtools/samtools_stats/samtools_stats.xml
- tool_collections/samtools/tool_dependencies.xml
also create a symlink for tool_dependencies.xml
> bump samtools to v1.2 and use macros

- tools/bwa/bwa-mem.xml
> Bugfix for bwa-mem scoring options command creation.

- tool_collections/samtools/samtools_mpileup/samtools_mpileup.xml
Major cleanup of mpileup options. Removed test that were using cached data
> Cleanup of mpileup

- tools/cummeRbund/.shed.yml
fix https://github.com/galaxyproject/tools-devteam/issues/106
> Add .shed.yml file for cummeRbund

- data_managers/data_manager_build_kraken_database/.shed.yml
- data_managers/data_manager_build_kraken_database/data_manager/kraken_database_builder.xml
- data_managers/data_manager_build_kraken_database/data_manager/make_json.py
- data_managers/data_manager_build_kraken_database/data_manager_conf.xml
- data_managers/data_manager_build_kraken_database/tool_data_table_conf.xml.sample
- data_managers/data_manager_build_kraken_database/tool_dependencies.xml
Ping @blankenberg for obvious reasons.
> Add data manager to generate kraken databases.

- tools/table_annovar/table_annovar.xml
table_annovar can now produce an annotated VCF file in addition to a tabular file. This pull request enhances the table_annovar wrapper to produce a VCF file.
> Add option to table_annovar to output VCF.

- .travis.yml
- tool_collections/fastx_toolkit/fastq_to_fasta/fastq_to_fasta.xml
Makes travis quieter/easier to read, test the tools, and fail only on errors (not citation warnings
> Implement changes used by IUC

- tool_collections/galaxy_sequence_utils/fastq_combiner/fastq_combiner.xml
- tool_collections/galaxy_sequence_utils/fastq_filter/fastq_filter.xml
- tool_collections/galaxy_sequence_utils/fastq_groomer/fastq_groomer.xml
- tool_collections/galaxy_sequence_utils/fastq_manipulation/fastq_manipulation.xml
- tool_collections/galaxy_sequence_utils/fastq_masker_by_quality/fastq_masker_by_quality.xml
- tool_collections/galaxy_sequence_utils/fastq_paired_end_joiner/fastq_paired_end_joiner.xml
- tool_collections/galaxy_sequence_utils/fastq_paired_end_splitter/fastq_paired_end_splitter.xml
- tool_collections/galaxy_sequence_utils/fastq_stats/fastq_stats.xml
- tool_collections/galaxy_sequence_utils/fastq_to_tabular/fastq_to_tabular.xml
- tool_collections/galaxy_sequence_utils/fastq_trimmer/fastq_trimmer.xml
- tool_collections/galaxy_sequence_utils/fastqtofasta/fastq_to_fasta.xml
- tool_collections/galaxy_sequence_utils/tabular_to_fastq/tabular_to_fastq.xml
- tools/ccat/ccat_wrapper.xml
- tools/fastq_trimmer_by_quality/fastq_trimmer_by_quality.xml
- tools/filter_transcripts_via_tracking/filter_transcripts_via_tracking.xml
- tools/sicer/sicer_wrapper.xml
- tools/velvet/macros.xml
- tools/velvet/velvetg.xml
- tools/velvet/velveth.xml
Hi,
in the ccatwrapper is mentioned:
"If you use this tool in Galaxy, please cite Blankenberg D, et al. *In preparation.*"
Is it still in preparation?
Best
Anika
> Citations and documentation improvements

- tools/bwa/bwa-mem.xml
- tools/bwa/bwa.xml
- tools/bwa/bwa_macros.xml
fixes hopefully https://github.com/galaxyproject/tools-devteam/issues/157
> Add stdio macro and catch more errors.

- tools/freebayes/freebayes.xml
> Fix --report_monomorphic for freebayes full options.

- tools/bwa/bwa-mem.xml
- tools/bwa/bwa.xml
- tools/bwa/bwa_macros.xml
BWA tool now adds the dbKey of the reference sequence to the output bam.
PS: This repo is newer than what is on the toolshed, right? When do you update the toolshed?
> bwa - add dbKey to output bwa

- tool_collections/kraken/kraken/kraken.xml
- tool_collections/kraken/kraken_report/kraken-mpa-report.xml
kraken actually works now. added kraken-mpa-report. still need to add tests
> Kraken update2

- data_managers/data_manager_build_kraken_database/data_manager/kraken_database_builder.xml
- tool_collections/kraken/kraken/kraken.xml
- tool_collections/kraken/kraken_filter/kraken-filter.xml
- tool_collections/kraken/kraken_report/kraken-report.xml
- tool_collections/kraken/kraken_translate/kraken-translate.xml
- tool_collections/kraken/macros.xml
- tools/cd_hit_dup/cd_hit_dup.xml
Set the kraken DB path in an environment variable.
Remove the histogram output definition.
Fix for when no external FASTA files are defined.
> Minor updates to kraken.

- packages/package_gb_taxonomy_8d245994d7/tool_dependencies.xml
> Use github magic to download tarball.

- tools/weblogo3/rgWebLogo3.xml
This should address: https://github.com/galaxyproject/tools-devteam/issues/141
> Fix output format

- tool_collections/cufflinks/cufflinks/cufflinks_wrapper.py
- tools/tophat/tophat_wrapper.xml
- tools/tophat2/tophat2_wrapper.xml
> TopHat and Cufflinks fixes.

- tool_collections/cufflinks/cuffcompare/cuffcompare_wrapper.xml
> Update cuffcompare documentation

- tools/bowtie2/bowtie2_wrapper.xml
This PR should rebase https://github.com/galaxyproject/tools-devteam/pull/59 so we can merge it.
> Rebase #59

- tools/bowtie2/bowtie2_wrapper.xml
Added option to produce SAM output rather than sorted BAM.
> add option to output SAM from bowtie2

- packages/package_rmap_2_05/tool_dependencies.xml
> fix rmap URL

- tools/picard/picard_CollectAlignmentSummaryMetrics.xml
fixes: https://github.com/galaxyproject/tools-devteam/issues/244
> Change METRIC_ACCUMULATION_LEVEL to a list of multiple values

- tools/picard/picard_SortSam.xml
for @jennaj and https://github.com/galaxyproject/tools-devteam/issues/160
> remove "unsorted" option from picard SortSam

- tools/bwa/bwa-mem.xml
- tools/bwa/bwa.xml
- tools/bwa/bwa_macros.xml
- tools/bwa/tool_dependencies.xml
This version of BWA is not compatible with samtools 1.1, but is compatible with samtools 1.2
> Update BWA to use samtools 1.2.

- tools/varscan_version_2/varscan_mpileup.xml
And some other tweaks to make planemo pass
> VarScan 2: added citation

- macros/read_group_macros.xml
Creating a WIP for this so I don't forget.
> [WIP] Fix small bug in read_group_macros.xml.

- tool_collections/bamtools/bamtools/bamtools.xml
- tool_collections/bamtools/bamtools_filter/bamtools-filter.xml
- tool_collections/bamtools/bamtools_split/bamtools-split.xml
- tool_collections/cufflinks/cuffquant/cuffquant_wrapper.xml
- tool_collections/samtools/samtools_mpileup/samtools_mpileup.xml
- tool_collections/vcflib/vcfcombine/vcfcombine.xml
- tool_collections/vcftools/vcftools_isec/vcftools_isec.xml
- tool_collections/vcftools/vcftools_merge/vcftools_merge.xml
In support of https://github.com/galaxyproject/tools-iuc/issues/239
> Swap all repeats to multiple='True' where appropriate

- suites/suite_fastx_toolkit_0_0_13/repository_dependencies.xml
- suites/suite_gatk_1_4/repository_dependencies.xml
- suites/suite_gops_1_0/repository_dependencies.xml
- suites/suite_samtools_0_1_18/repository_dependencies.xml
- suites/suite_samtools_0_1_19/repository_dependencies.xml
need to check whether Planemo automatically strips these on upload or not
> revert stripping the changeset_revisions from versioned suites

- suites/suite_kraken_0_10_5/repository_dependencies.xml
> Fix Kraken suite description.

- tools/bowtie2/bowtie2_wrapper.xml
- tools/bowtie2/tool_dependencies.xml
depended on https://github.com/galaxyproject/tools-iuc/pull/391
> update wrapper to version 2.2.6

- tools/bowtie2/tool_dependencies.xml
Fix #290.
Please merge and push to the Tool Sheds as soon as possible!
> Fix samtools package version in bowtie2/tool_dependencies.xml .

- tools/cd_hit_dup/cd_hit_dup.xml
xref https://github.com/galaxyproject/tools-devteam/issues/273
ping @nekrut 
closes #273
> Clarify cd-hit-dup help that chimeric filter only available for single reads.

- packages/package_rpy_1_0_3/tool_dependencies.xml
- tools/scatterplot/scatterplot.py
- tools/scatterplot/scatterplot.xml
- tools/scatterplot/tool_dependencies.xml
Add numpy as requirement for rpy and scatterplot.
Should fix #282.
Not tested!
> Explicitly import array from numpy in scatterplot tool.

- legacy/package_cairo_1_12_14/tool_dependencies.xml
xref: https://github.com/galaxyproject/tools-iuc/pull/462
> Disable quartz and add fontconfig to cairo dependencies.

- tools/column_maker/column_maker.xml
Not sure how to represent such a bulk of items ... a list seems to long to me.
> add a list of all build-in functions

- tools/cut_columns/cutWrapper.pl
- tools/cut_columns/cutWrapper.xml
see also: https://github.com/galaxyproject/galaxy/pull/913
> Update Cut tool to match distribution.

- tool_collections/cufflinks/gffread/gffread.xml
change at L212 - the rest is whitespace
> Remove gffread optional

- tools/table_annovar/table_annovar.xml
Changed display of params to radio button to increase the visibility of possible option, current version only shows an empty field with a "check/uncheck" box.
> changed display of params

- legacy/package_freetype_2_5_2/tool_dependencies.xml
Hi,
zlib rule them all.
So, I add a dependency to zlib.
Cheers
> freetype also need zlib

- data_managers/data_manager_bwa_mem_index_builder/data_manager/bwa_mem_index_builder.xml
- data_managers/data_manager_bwa_mem_index_builder/tool_dependencies.xml
Since 0.7.10.039ea20639 is not availble for OS X.
> Upgrade bwa_mem_index_builder's bwa dependency to 0.7.12

- .tt_blacklist
- tools/tophat2/tool_dependencies.xml
- tools/tophat2/tophat2_wrapper.xml
> Add auto option to coverage_search conditional in TopHat

- .tt_blacklist
- tools/fasta_compute_length/fasta_compute_length.xml
- tools/fasta_concatenate_by_species/fasta_concatenate_by_species.xml
- tools/fasta_filter_by_length/fasta_filter_by_length.xml
- tools/fasta_to_tabular/fasta_to_tabular.xml
- tools/tabular_to_fasta/tabular_to_fasta.xml
Need to trigger a test here. But these repos should be ready for testing as they do not have dependency or only bx-python.
> Test more tools by default

- data_managers/data_manager_build_kraken_database/data_manager/kraken_database_builder.xml
- data_managers/data_manager_build_kraken_database/tool_dependencies.xml
Fixes ftp download location changes at NCBI
> Update Kraken Data Manager to use Kraken version 0.10.6-eaf8fb68.

- legacy/package_libpng_1_6_7/tool_dependencies.xml
Hi,
The same: https://github.com/galaxyproject/tools-iuc/pull/545
It's seem that libpng need zlib so I just add a dependency.
Cheers
Gildas
> libpng need zlib

- tools/samtool_filter2/samtool_filter2.xml
There's a samflag 0x0800 for supplementary reads that I'd like to use on galaxy. Thanks!!
> Adding "supplementary reads" filter to samtools filter

- .travis.yml
- .tt_blacklist
- tools/scatterplot/scatterplot.py
- tools/scatterplot/scatterplot.xml
- tools/scatterplot/tool_dependencies.xml
Depends on https://github.com/galaxyproject/cargo-port/pull/97 and https://github.com/galaxyproject/tools-iuc/pull/921 and closes #385
> Update scatterplot tool for rpy2

- tool_collections/vcflib/tool_dependencies.xml
- tool_collections/vcflib/vcf2tsv/tool_dependencies.xml
- tool_collections/vcflib/vcfaddinfo/tool_dependencies.xml
- tool_collections/vcflib/vcfallelicprimitives/tool_dependencies.xml
- tool_collections/vcflib/vcfannotate/tool_dependencies.xml
- tool_collections/vcflib/vcfannotategenotypes/tool_dependencies.xml
- tool_collections/vcflib/vcfbedintersect/tool_dependencies.xml
- tool_collections/vcflib/vcfbreakcreatemulti/tool_dependencies.xml
- tool_collections/vcflib/vcfcheck/tool_dependencies.xml
- tool_collections/vcflib/vcfcombine/tool_dependencies.xml
- tool_collections/vcflib/vcfcommonsamples/tool_dependencies.xml
- tool_collections/vcflib/vcfdistance/tool_dependencies.xml
- tool_collections/vcflib/vcffilter/tool_dependencies.xml
- tool_collections/vcflib/vcffixup/tool_dependencies.xml
- tool_collections/vcflib/vcfflatten/tool_dependencies.xml
- tool_collections/vcflib/vcfgeno2haplo/tool_dependencies.xml
- tool_collections/vcflib/vcfgenotypes/tool_dependencies.xml
- tool_collections/vcflib/vcfhethom/tool_dependencies.xml
- tool_collections/vcflib/vcfleftalign/tool_dependencies.xml
- tool_collections/vcflib/vcfprimers/tool_dependencies.xml
- tool_collections/vcflib/vcfrandomsample/tool_dependencies.xml
- tool_collections/vcflib/vcfselectsamples/tool_dependencies.xml
- tool_collections/vcflib/vcfvcfintersect/tool_dependencies.xml
as the TS package does not exist in this version anymore; we rely solely on Conda here from now on
@bgruening @mvdbeek
> remove the incorrect tool_dependencies.xml

- tools/picard/picard_AddCommentsToBam.xml
- tools/picard/picard_AddOrReplaceReadGroups.xml
- tools/picard/picard_BedToIntervalList.xml
- tools/picard/picard_CleanSam.xml
- tools/picard/picard_CollectAlignmentSummaryMetrics.xml
- tools/picard/picard_CollectBaseDistributionByCycle.xml
- tools/picard/picard_CollectGcBiasMetrics.xml
- tools/picard/picard_CollectInsertSizeMetrics.xml
- tools/picard/picard_CollectRnaSeqMetrics.xml
- tools/picard/picard_CollectWgsMetrics.xml
- tools/picard/picard_DownsampleSam.xml
- tools/picard/picard_EstimateLibraryComplexity.xml
- tools/picard/picard_FilterSamReads.xml
- tools/picard/picard_MarkDuplicates.xml
- tools/picard/picard_MarkDuplicatesWithMateCigar.xml
- tools/picard/picard_MeanQualityByCycle.xml
- tools/picard/picard_NormalizeFasta.xml
- tools/picard/picard_QualityScoreDistribution.xml
- tools/picard/picard_ReorderSam.xml
- tools/picard/picard_ReplaceSamHeader.xml
- tools/picard/picard_SamToFastq.xml
- tools/picard/picard_SortSam.xml
- tools/picard/picard_ValidateSamFile.xml
- tools/picard/picard_macros.xml
> Escape element identifiers in picard

- .travis.yml
The 16.10 release is a-happenin'.
> Test against 16.10

- tools/bwa/bwa-mem.xml
- tools/bwa/bwa.xml
- tools/bwa/bwa_macros.xml
- tools/bwa/tool_dependencies.xml
upgrade bwa to 0.7.15, samtools to 1.3.1 and drop toolshed dependencies.
> Add nanopore and contig mode to bwa-mem

- tool_collections/gatk/variant_filtration/variant_filtration.xml
- tool_collections/gatk/variant_select/variant_select.xml
http://dev.list.galaxyproject.org/no-reference-genome-list-in-variant-selector-tool-td4666145.html
A little old, but worth merging.
> Fix for cached reference genome selector

- tools/bowtie2/bowtie2_wrapper.xml
upgrade to bowtie 2.2.8, upgrade samtools to 1.3.1 and add multi-threading when indexing.
> Bring bowtie2 up to current standards

- tool_collections/bamtools/bamtools_filter/bamtools-filter.xml
> fix bamtools filter to accept negative numbers in the insert size filter

- tool_collections/vcflib/vcfrandomsample/vcfrandomsample.xml
- tool_collections/vcflib/vcfsort/vcfsort.xml
- tool_collections/vcflib/vcfvcfintersect/vcfvcfintersect.xml
Fix typos and indentation
Use '&&' to concatenate commands
> Lint vcflib tools

- tool_collections/gops/flanking_features/flanking_features.xml
- tool_collections/gops/intersect/intersect.xml
- tool_collections/gops/subtract/subtract.xml
- tool_collections/hgv/hgv_hilbertvis/.shed.yml
- tool_collections/hgv/hgv_hilbertvis/hilbertvis.xml
- tools/samtool_filter2/.shed.yml
- tools/samtool_filter2/samtool_filter2.xml
xref. https://github.com/galaxyproject/galaxy/issues/3353
Also update a bit the affected tools to recent standard.
> Replace isinstance with is_of_type

- packages/package_weblogo_3_3/tool_dependencies.xml
Fix https://github.com/galaxyproject/galaxy/issues/3574
> Fix weblogo download URL

- tool_collections/cufflinks/cuff_macros.xml
- tool_collections/cufflinks/cuffcompare/cuffcompare_wrapper.py
- tool_collections/cufflinks/cuffcompare/cuffcompare_wrapper.xml
- tool_collections/cufflinks/cuffdiff/cuffdiff_wrapper.xml
- tool_collections/cufflinks/cufflinks/cufflinks_wrapper.py
- tool_collections/cufflinks/cufflinks/cufflinks_wrapper.xml
- tool_collections/cufflinks/cuffmerge/cuffmerge_wrapper.py
- tool_collections/cufflinks/cuffmerge/cuffmerge_wrapper.xml
- tool_collections/cufflinks/cuffnorm/cuffnorm_wrapper.xml
- tool_collections/cufflinks/cuffquant/cuffquant_wrapper.xml
- tool_collections/cufflinks/gffread/gffread.xml
The PR aims to prepare cufflinks tool_collection to be conda ready.
###Cufflinks
I had deps for lib/galaxy/datatypes/util/gff_util.py which is called by [cufflinks_wrapper.py ](https://github.com/lecorguille/tools-devteam/blob/e9cb7de8b3789ecf6710faff54c88bb771b28a2d/tool_collections/cufflinks/cufflinks/cufflinks_wrapper.py#L9)
(it was tricky to solve because it seems a Galaxy library (so usually run in the .venv) but it's actually launched within the conda environment)
###Cuffdiff
I had to change the package name to fit with conda nomenclature.
I can change easily the ToolShed tooldependency package_cummerbund_2_8_2 from IUC to fit also with the conda nomenclature!?
https://github.com/galaxyproject/tools-iuc/blob/master/packages/package_cummerbund_2_8_2/tool_dependencies.xml#L9
```xml …
```
> Cufflinks conda

- tools/featurecounter/featureCounter.xml
> Corrected example text in featureCounter.xml

- tools/scatterplot/scatterplot.py
- tools/scatterplot/scatterplot.xml
* the open() one is important for py3k
> Scatterplot updates

- .travis.yml
- tools/bwa/bwa-mem.xml
- tools/bwa/bwa_macros.xml
depends on https://github.com/bioconda/bioconda-recipes/pull/6663
> Update bwa-mem to 0.7.17

- tool_collections/galaxy_sequence_utils/fastq_trimmer/fastq_trimmer.xml
Just a little typo I found while updating our server
> Fastq_trimmer: fix typo in datatype

- tools/tophat_fusion_post/tophat_fusion_post.xml
> this tool seems to be broken

- tool_collections/gops/coverage/coverage.xml
- tool_collections/gops/join/join.xml
I broke these in commit cae3e05d02e60f595bb8b6d77a84f030e9bd1689 .
> Fix output format for coverage and join

- tool_collections/galaxy_sequence_utils/fastq_combiner/fastq_combiner.xml
- tool_collections/galaxy_sequence_utils/fastq_filter/fastq_filter.xml
- tool_collections/galaxy_sequence_utils/fastq_groomer/fastq_groomer.xml
- tool_collections/galaxy_sequence_utils/fastq_manipulation/fastq_manipulation.xml
- tool_collections/galaxy_sequence_utils/fastq_masker_by_quality/fastq_masker_by_quality.xml
- tool_collections/galaxy_sequence_utils/fastq_paired_end_deinterlacer/fastq_paired_end_deinterlacer.xml
- tool_collections/galaxy_sequence_utils/fastq_paired_end_interlacer/fastq_paired_end_interlacer.xml
- tool_collections/galaxy_sequence_utils/fastq_paired_end_joiner/fastq_paired_end_joiner.xml
- tool_collections/galaxy_sequence_utils/fastq_paired_end_splitter/fastq_paired_end_splitter.xml
- tool_collections/galaxy_sequence_utils/fastq_stats/fastq_stats.xml
- tool_collections/galaxy_sequence_utils/fastq_to_tabular/fastq_to_tabular.xml
- tool_collections/galaxy_sequence_utils/fastq_trimmer/fastq_trimmer.xml
- tool_collections/galaxy_sequence_utils/fastqtofasta/fastq_to_fasta.xml
- tool_collections/galaxy_sequence_utils/tabular_to_fastq/tabular_to_fastq.xml
The aim of this pull request is to add the edam ontology tags to `galaxy_sequence_utils`.
> Add edam ontology

- tools/categorize_elements_satisfying_criteria/categorize_elements_satisfying_criteria.xml
> Fix typo catergories -> categories

- tools/fasta_compute_length/fasta_compute_length.xml
- tools/fasta_compute_length/utils/fasta_to_len.py
- tools/fasta_concatenate_by_species/utils/maf_utilities.py
- tools/fasta_to_tabular/fasta_to_tabular.xml
> Bump fasta_compute_length version, drop version assertions

- tools/merge_cols/mergeCols.py
- tools/merge_cols/mergeCols.xml
Hi devteam, this tool isn't working due to python2 print statements.
Catherine, Galaxy Australia
> python3 print statements for mergeCols.py

- .github/workflows/ci.yaml
- .github/workflows/pr.yaml
- setup.cfg
- tools/windowsplitter/tool_dependencies.xml
- tools/windowsplitter/windowSplitter.py
- tools/windowsplitter/windowSplitter.xml
Also:
- Update `bx-python` dependency
- Remove `tool_dependencies.xml`
> Add Python 3 support to windowSplitter

- .github/workflows/ci.yaml
- .github/workflows/pr.yaml
- planemo test uses --no_dependency_resolution
- cache v2
- R linting
> sync ci workflows with IUC

- .tt_skip
- tools/megablast_xml_parser/megablast_xml_parser.py
- tools/megablast_xml_parser/megablast_xml_parser.xml
- tools/megablast_xml_parser/repository_dependencies.xml
If that passes can I request a review @peterjc :)
> py3k megablast

- .github/workflows/ci.yaml
- .github/workflows/pr.yaml
- .github/workflows/slash.yaml
- README.md
> sync github actions workflows with current IUC state

- tools/sicer/.shed.yml
- tools/sicer/sicer_wrapper.py
- tools/sicer/sicer_wrapper.xml
Fix:
```
except Exception, e:
^
SyntaxError: invalid syntax
````
Also cleanup wrapper and script.
> Fix Python2-only syntax in sicer tool

- .tt_skip
- tools/pileup_interval/pileup_interval.py
- tools/pileup_interval/pileup_interval.xml
Came up in containerized tool tests. This makes it run. Alternative is setting py 2 requirement.
> [pileup_interval] py2 -> py3

- .github/workflows/ci.yaml
- .github/workflows/pr.yaml
> switch workflows to 21.05

- .tt_skip
- tools/ucsc_custom_track/build_ucsc_custom_track.py
- tools/ucsc_custom_track/build_ucsc_custom_track.xml
- tools/ucsc_custom_track/build_ucsc_custom_track_code.py
Fix https://github.com/galaxyproject/tools-devteam/issues/604
Also:
- Fix indentation and spaces
- Don't use `interpreter` attribute of `<command>`
- Add CDATA to `command` and `help` content
- Add python 3.10 requirement
- Use single quotes for text and data params in Cheetah code
- Use `with` statement to open/close files
- Flake8 fixes
> Port ucsc_custom_track to Python 3

- .github/workflows/ci.yaml
- .github/workflows/pr.yaml
ToolShed uploads are currently not being performed because the deploy job checks only for the `master` branch name.
> Sync CI workflows with tools-iuc

- tool_collections/taxonomy/gi2taxonomy/gi2taxonomy.xml
Hi all,
This PR links the tools to its bio.tools entry: https://bio.tools/gi2taxonomy
It will be useful to get EDAM ontology annotations
Engy
> Update gi2taxonomy.xml adding tool id from biotools

- tool_collections/taxonomy/t2ps/.shed.yml
- tool_collections/taxonomy/t2ps/t2ps_wrapper.xml
Hi all,
This PR links the tools to its bio.tools entry: https://bio.tools/t2ps
It will be useful to get EDAM ontology annotations
Engy
> Add bio.tools for t2ps
