tools/bowtie_wrappers/bowtie_wrapper.py, tools/bowtie_wrappers/bowtie_wrapper.xml
When specifying both -n and -v options, bowtie considers only the last one.
Moreover:
- show fields for -e, -l and --nomaqround options only for -n alignment
- min value for -e is 1 not 0
- possible values for -v are 0, 1, 2, 3
Tool version is not incremented because it was already in commit 8991438139974fb52c878401885dbdfb6a0a5bc0 and then not released on the Tool Shed.
All tests pass in Planemo, but I had to create a ```tool_data_table_conf.xml.test``` file and copy the ```equCab2chrM/bowtie/``` directory (8.1 Mb) from https://bitbucket.org/natefoo/galaxy-test-data/ . Is there interest in moving these test files in this repo? @jmchilton
=> Add conditional to choose between -n and -v alignment modes.

tools/fastqc/rgFastQC.py
With for example a bam file that does not have its extension in its history name fastqc will fail with a message that indicates that it tries to read a fastq instead of bam(see below). This patch fixes this.
Fatal error: Exit code 1 ()
Failed to process Filtered_BAM_file1_bowtie2
uk.ac.babraham.FastQC.Sequence.SequenceFormatException: ID line didn't start with '@'
at uk.ac.babraham.FastQC.Sequence.FastQFile.readNext(FastQFile.java:158)
at uk.ac.babraham.FastQC.Sequence.FastQFile.<init>(FastQFile.java:89)
at uk.ac.babraham.FastQC.Sequence.SequenceFactory.getSequenceFile(SequenceFactory.java:104)
at uk.ac.babraham.FastQC.Sequence.SequenceFactory.getSequenceFile(SequenceFactory.java:62)
at uk.ac.babraham.FastQC.Analysis.OfflineRunner.processFile(OfflineRunner.java:122)
at …
=> Fastqc: fix format detection when history name does not incl. the extension

tools/bowtie2/bowtie2_wrapper.xml
It should not work, at least all other parameters behave differently. See also https://github.com/galaxyproject/galaxy/commit/cf8fd5c5970b0bc5f6dd4f8a9af710a29d90f2e4.
=> This is not strictly needed, but we are not sure why this is working.

data_managers/data_manager_gatk_picard_index_builder/data_manager/data_manager_gatk_picard_index_builder.xml
NB: We should determine if this used to work as-is, and if some job running change in Galaxy broke this tool.
Example of behavior, notice that the arguments after a \ have a space prepended before the '--argname':
argv ['/path/galaxy-blankenberg/installed/toolshed.g2.bx.psu.edu/repos/devteam/data_manager_gatk_picard_index_builder/a15709ad26ea/data_manager_gatk_picard_index_builder/data_manager/data_manager_gatk_picard_index_builder.py', '/path/galaxy-blankenberg/database/files/000/dataset_4.dat', ' --jar', '/path/shed_tools/galaxy-blankenberg/tool_dependency_dir/picard/1.56.0/devteam/package_picard_1_56_0/99a28567c3a3/jars/CreateSequenceDictionary.jar', ' --fasta_filename', '/path/galaxy-blankenberg/tool-data/hg19/seq/hg19.fa', ' --fasta_dbkey', 'hg19', ' --fasta_description', 'hg19', ' …
=> Remove line continuation char (\) from GATK Picard Index Data Manager

tools/bwa/bwa-mem.xml, tools/bwa/bwa.xml
Redirect stderr of stat to /dev/null .
Quote shell variables in tests.
=> Correct test for OS X since 'eval $()' always exits with 0. Fix #81.

packages/package_galaxy_utils_1_0/tool_dependencies.xml
This ensures that libraries are installed into `$HOME/lib64`.
=> fix installation where python will install libraries into `$HOME/lib64`

tools/samtool_filter2/samtool_filter2.xml
Detect command errors.
Use CDATA.
Quote data file paths in command.
Add argument names to parameters' help.
Remove trailing whitespaces.
=> samtool_filter2 cleanup.

tools/tophat2/tophat2_wrapper.xml
Useful to extract unmapped reads for further analysis (i.e. identification of expressed viral sequences from human RNA-Seq data)
=> Add option for reporting unmapped.bam

tools/microsatellite_birthdeath/microsatellite_birthdeath.xml
The dashed line is being treated as marker for a section header instead of as an horizontal line.
=> Correct reStructuredText typo

tool_collections/samtools/samtools_mpileup/samtools_mpileup.xml
Fixes https://trello.com/c/ykmEqNYQ/2664-bug-mpileup-bad-parameter .
Also:
- add help to `region_string` param
- use complete "path" for 2 variables in Cheetah
- fix indentation
=> Restore region_string param in samtools_mpileup.

tool_collections/bamtools/bamtools_split/bamtools-split.xml, tools/mine/MINE.xml
Two tools were missing tags causing warnings when parsed by galaxy.
=> Silence warnings due to missing <when> tags

tool_collections/cufflinks/cuff_macros.xml
Cufflinks can produce the following error message and this isn't catched by the current stdio tag.
```
Error running cufflinks.
return code = -11
Command line:
```
=> Adopt for cufflinks error message

tools/picard/picard_MarkDuplicatesWithMateCigar.xml
The functional test for this tool fails.  Looking at the XML wrapper, it looks like $comments is invalid....it doesn't exist anywhere else in the xml file.  I know that comments can be specified multiple times however there is no way to get the comments fields to appear multiple times in the UI as far as I can tell.  This change allows the comment to be added and still pass.
=> Fix failed functional test

tools/picard/picard_MergeBamAlignment.xml
Line 128 specifies a parameter named read2_aligned_bam from the read2_aligned_bams repeat block. On line 43, this parameter is referenced as "read1_aligned_bam." Whether or not this makes a difference is beyond my understanding of the internals, but consistency is desirable. Alternatively, if this is not managed behind the scenes by the galaxy library then this would have produced incorrect output in the past.
=> Correct line 43 of picard_MergeBamAlignment.xml

packages/package_libxml2_2_9_1/tool_dependencies.xml
I had trouble using libxml2 from my blast2html tool which is written in python. Currently I'm using a private fork of package_libxml2_2_9_1 but I would prefer to use the mainline one. 
The changes are setting LD_LIBRARY_PATH, LIBRARY_PATH, C_INCLUDE_PATH and CPLUS_INCLUDE_PATH. That allows pip to find the right location of the binary and headers to install the lxml module in the venv that my tool builds.
=> Add more environment variables to libxml2

packages/package_libxslt_1_1_28/tool_dependencies.xml
This is needed so that python can find the library. LD_LIBRARY_PATH is needed for runtime loading of the lxml module, the others to build the
lxml module correctly.
Without this lxml will build against the system libraries, so everything would appear to work if the libxslt/libxml2 development files are
installed.
=> Add extra environment vars to libxslt

tools/bwa/bwa-mem.xml, tools/bwa/bwa.xml, tools/bwa/bwa_macros.xml
the `\t` gets replaced with a real tab and messes up the run/bam file because the `@PG` line gets crappy.
Using `\\t`, like also recommended by bwa [1] fixes this.
[1] http://bio-bwa.sourceforge.net/bwa.shtml
=> bwa - fixing malformed header because of readgroups

data_managers/data_manager_sam_fasta_index_builder/data_manager/data_manager_sam_fasta_index_builder.py
samtools faidx provides a 0 return code when the fasta input file is missing. This will cause the tool to properly enter an error state.
=> data_manager_sam_fasta_index_builder error on missing fasta file

tools/bowtie2/bowtie2_wrapper.xml
Closes #97 but requires updates to galaxy (specifically see galaxyproject/galaxy#544).
Do we hate the syntax or does it look fine - the conditional outputs aren't new (I found uses of them in gatk for instance) - the new stuff is digging into the collection using the XML attributes.
=> Fix Bowtie 2 wrapper for unaligned reads for collected pairs.

packages/package_cufflinks_2_1_1/tool_dependencies.xml, packages/package_cufflinks_2_2_1/tool_dependencies.xml
These are 404:
- http://cufflinks.cbcb.umd.edu/downloads/cufflinks-2.1.1.tar.gz
- http://cufflinks.cbcb.umd.edu/downloads/cufflinks-2.2.1.tar.gz
Only the links for the binary packages had previously been updated, see https://github.com/galaxyproject/tools-devteam/commit/f00c3318751dab6a608688a8706798a27cd883ba (@martenson) and https://github.com/galaxyproject/tools-devteam/commit/804f9e6a17882f1353fe0a82692ca887c5a6e3da (@bgruening)
Found while testing ``planemo dependencies_script`` - see https://github.com/galaxyproject/planemo/pull/310
=> Update download urls for cufflinks source code

packages/package_tophat2_2_0_9/tool_dependencies.xml, packages/package_tophat_1_4_0/tool_dependencies.xml
These are 404:
- http://tophat.cbcb.umd.edu/downloads/tophat-1.4.0.tar.gz
- http://tophat.cbcb.umd.edu/downloads/tophat-2.0.9.tar.gz
Note there is a ``tophat-1.4.0.1.tar.gz`` available on http://ccb.jhu.edu/software/tophat/downloads/ which I suspect was a minor Linux fix, but this is not mentioned here: https://ccb.jhu.edu/software/tophat/index.shtml
Found while testing planemo dependencies_script - see galaxyproject/planemo#310
=> Update tophat source code URLs

tools/freebayes/freebayes.xml
Fixing issue when 'optional_inputs' is not selected and then complain it cannot find 'report_monomorphic'.  parameter. Moved it to be under all other parameter that only show up when 'optional_inputs' is selected.
Example of stacktrace
Traceback (most recent call last):
File "/Applications/galaxy/production/galaxy-dist/lib/galaxy/jobs/runners/__init__.py", line 163, in prepare_job
job_wrapper.prepare()
File "/Applications/galaxy/production/galaxy-dist/lib/galaxy/jobs/__init__.py", line 859, in prepare
self.command_line, self.extra_filenames, self.environment_variables = tool_evaluator.build()
File "/Applications/galaxy/production/galaxy-dist/lib/galaxy/tools/evaluation.py", line 422, in build
raise e
NotFound: cannot find 'report_monomorphic' while searching for …
=> Errror when not using "optional_inputs" flag with 'report_monomorphic flag'

tool_collections/cufflinks/cuffdiff/cuffdiff_wrapper.xml
--quiet is not implemented, this causes progress bar output to be dumped into log data.  It is implemented elsewhere, for example line 107 here:
https://github.com/galaxyproject/tools-devteam/blob/master/tool_collections/cufflinks/cufflinks/cufflinks_wrapper.py#L107
=> added --quiet to suppress progress bar, filling up logs

tool_collections/galaxy_sequence_utils/fastq_manipulation/fastq_manipulation.xml, tool_collections/galaxy_sequence_utils/fastq_trimmer/fastq_trimmer.py, tool_collections/galaxy_sequence_utils/fastq_trimmer/fastq_trimmer.xml
This will allow removing all sequence to the right of the absolute value of the provided negative position. 
IOW: a negative value will do the same as the standard python slice with the positive value.
ping @nekrut
=> Allow FASTQ trimmer to accept negative values for right-hand offset.

legacy/package_cairo_1_12_14/tool_dependencies.xml
Same as https://github.com/galaxyproject/tools-iuc/pull/452
Ping @martenson
=> Remove double ampersand that remained after switching to autoconf

tools/bwa/.shed.yml, tools/bwa/bwa-mem.xml, tools/bwa/bwa.xml, tools/bwa/bwa_macros.xml, tools/bwa/tool_dependencies.xml
The versions of these tools have been updated to be 0.4.2.
=> Fix the BWA tools to require version 0.7.12 of the BWA package.

tools/bowtie2/bowtie2_wrapper.xml, tools/bowtie2/test-data/bowtie2-stats.out, tools/bowtie_wrappers/bowtie_wrapper.py, tools/bowtie_wrappers/bowtie_wrapper.xml, tools/bowtie_wrappers/test-data/bowtie_out11.txt
By default the `bowtie_wrapper` and `bowtie2` tools don't keep the stderr output from the underlying `bowtie` and `bowtie2` programs, however this contains useful statistics on the mapping.
This PR adds an option to both tools that, when selected, saves these statistics as a history item when the tools are run. (There are also new test cases, however I haven't been able to get these or the existing tests to pass.)
Adding this functionality has previously been discussed on this Trello card:
https://trello.com/c/TdYxdbkm
which also contains my original patch for the`bowtie_wrapper`. I've returned to this now I have users who are interested in having this functionality in our local Galaxy instance, however the thread on Trello suggests that others might also find it useful.
Thanks for …
=> Add option to Bowtie & Bowtie2 to keep statistics from stderr

tool_collections/galaxy_sequence_utils/fastq_paired_end_joiner/fastq_paired_end_joiner.py, tool_collections/galaxy_sequence_utils/fastq_paired_end_joiner/fastq_paired_end_joiner.xml, tool_collections/galaxy_sequence_utils/fastq_paired_end_joiner/tool_dependencies.xml
WIP due to package not existing yet. 
xref https://github.com/galaxyproject/sequence_utils/pull/2
=> Allow the FASTQ joining tool to use provided string of bases between joined reads.

tools/bwa/bwa-mem.xml, tools/bwa/bwa.xml
Also use CDATA in `<command>`.
Partially fix #312.
Testing by an OS X user would be appreciated.
=> Fail the job if bwa index fails.

tools/bwa/bwa-mem.xml, tools/bwa/bwa.xml, tools/bwa/bwa_macros.xml
My users have been bitten again by the failure of BWA indexing when using a big reference genome with long sequences from the history.
```
[bwa_index] Pack FASTA... 26.13 sec
[bwa_index] Construct BWT for the packed sequence...
[is_bwt] Failed to allocate -7621388068 bytes at is.c line 211: Cannot allocate memory
```
With this patch the trick of calculating the genome size is substituted by a new param which let the user choose the indexing algorithm and by defaults let BWA decide which is the best algorithm for the genome, which seems to work better than the genome size criterion.
=> BWA: Add param for reference indexing algorithm.

tool_collections/samtools/samtools_mpileup/samtools_mpileup.xml
The input bam files need to have the associated indexes.  So using the model from the freebayes tool, symlink the inputs bams ans their associated indexes into the job working directory.
=> Update samtools_mpileup to symlink bam and bai

tools/bowtie2/bowtie2_wrapper.xml
bowtie2 supports outputting aligned reads into separate files, this PR implements this functionality. This considerably speeds up a pipeline we are working on that repeatedly extracts aligned reads ( as compared to bowtie2 -> bam -> reads ).
=> Implement --al / --al-conc option for bowtie2

tool_collections/cufflinks/cuffcompare/cuffcompare_wrapper.xml, tool_collections/cufflinks/cufflinks/cufflinks_wrapper.xml, tool_collections/cufflinks/cuffmerge/cuffmerge_wrapper.xml
@natefoo on IRC:
> that reminds me, one of the tools that couldn't run on jetstream was due to its use of interpreter (which pulsar doesn't handle) 
> that tool (when I figure out which one it is) should be updated to use `$__tool_directory__`
it was one of the cuff* 
> cuffdiff maybe
This should fix all cufflinks tools.
=> Explicitly call python in command instead of using the depredated interpreter attribute

tool_collections/vcflib/vcfsort/vcfsort.xml
This should take care of the version string issue encountered in #391.
=> Add missing macros include to vcfsort

.tt_blacklist, tools/pileup_parser/.shed.yml, tools/pileup_parser/pileup_parser.pl, tools/pileup_parser/pileup_parser.xml
Hi, we fixed the pileup_parser.xml file because the pileup_parser.pl script contains a deprecated function (isdigit) which in our perl version (5.20.2) gives a warning (Calling POSIX::isdigit() is deprecated at pileup_parser.pl line 40, <IN> line 1. So the Galaxy job fails.
=> fixed wrapper

tool_collections/vcftools/vcftools_consensus/tool-data/fasta_indexes.loc.sample, tool_collections/vcftools/vcftools_consensus/tool_data_table_conf.xml.sample
Based on the error "This file requires an entry in the tool_data_table_conf.xml file. Upload a file named tool_data_table_conf.xml.sample to the repository that includes the required entry to correct this error." added tool_data_table_conf.xml.sample and associated files. This follows on PR #402.
=> vcftools_consensus:  Add tool_data_table_conf and associated files

tools/cummerbund/cummeRbund.xml
The --genes args are ignored by cummeRbund.R when generating a heatmap unless the --gene_selector argument is also included.
=> Add --gene_selector flag when generating heatmap with gene list

tools/bowtie2/bowtie2_wrapper.xml, tools/bowtie2/tool_dependencies.xml
I introduced this with https://github.com/galaxyproject/tools-devteam/pull/426, effectively breaking pre-indexed genomes.
=> Bowtie2 pre-indexed genomes fix, drop TS dependencies

tools/bowtie_color_wrappers/.shed.yml, tools/bowtie_color_wrappers/bowtie_color_wrapper.xml, tools/bowtie_color_wrappers/bowtie_wrapper.py, tools/bowtie_wrappers/.shed.yml, tools/bowtie_wrappers/bowtie_wrapper.py, tools/bowtie_wrappers/bowtie_wrapper.xml
Also:
- use `with` statement
- flake8 fixes.
Without these, `bowtie_wrappers` will not work with Conda dependencies if using Miniconda3.
Reported by @lparsons.
=> Fix Python3 compatibility for bowtie_wrappers and bowtie_color_wrappers

tools/fasta_filter_by_length/fasta_filter_by_length.xml
Specify that is greater than or equal to minimum and less than or equal to maximum. The ambiguity confused me while working in Galaxy.
=> Be more explicit in description

tools/samtool_filter2/samtool_filter2.xml
This fixes an issue when providing multiple regions divided by whitespace as written in the help. It would cause the tool to write in stdout a message e.g.: 
``[main_samview] region "chr1 chr2" specifies an unknown reference name. Continue anyway.``
as the cmd would read:
``samtools view -o '/galaxy/database/files/001/dataset_1885.dat' -h   -b  input.bam 'chr1 chr2' 2>&1``
Instead of:
``
samtools view -o '/galaxy/database/files/001/dataset_1888.dat' -h   -b  input.bam 'chr1' 'chr2' 2>&1
``
=> samtool_filter2: fix support for multiple region filter

.tt_skip, tools/merge_cols/mergeCols.py, tools/merge_cols/mergeCols.xml
I set out to fix what @yvanlebras reported on gitter:
```
There is an issue regarding the "Merge Columns" tool https://ecology.usegalaxy.eu/root?tool_id=toolshed.g2.bx.psu.edu/repos/devteam/merge_cols/mergeCols1/1.0.2 . Using 1.0.2 version, all the table is transformed as a one line file. Using 1.0.1 version https://ecology.usegalaxy.eu/root?tool_id=toolshed.g2.bx.psu.edu/repos/devteam/merge_cols/mergeCols1/1.0.1 is ok
history where you can look at this issue (dataset 14 with version 1.0.2, dataset 15 with 1.0.1): https://ecology.usegalaxy.eu/u/ylebras/h/test-training-session
```
I thought the issue was with `print(line, file=outfile)` not adding newlines,
but `\n` is actually the default end character. I can't reproduce Yvan's issue,
but might be a good idea to use `outfile.write()` with …
=> Some cosmetic changes to mergeCols

.github/workflows/ci.yaml, .github/workflows/pr.yaml
seems that the PR workflow does not work anymore, because of `set-env`. Guess its about time to sync the workflows again.
=> sync GH actions with IUC

tools/column_maker/column_maker.py, tools/column_maker/column_maker.xml
fixes https://github.com/galaxyproject/tools-devteam/issues/505
idea: 
- use inputs config file
- inject metadata (unfortunatelly that is not in the jsonfile)
- overwrite command line arguments (switched to argparse)
using json
=> allow larger number of columns for column maker

tool_collections/taxonomy/gi2taxonomy/gi2taxonomy.py, tool_collections/taxonomy/gi2taxonomy/gi2taxonomy.xml
The syntax `except Exception, e` was deprecated in python 3.
Reported at https://help.galaxyproject.org/t/error-with-fetch-taxonomic-representation/5145
=> Update exception handling in gi2taxonomy to be py3-compatible.

tools/column_maker/column_maker.py, tools/column_maker/column_maker.xml
Currently the tool fails when its input doesn't have at least one line of content, which is a nuisance with more complex WFs and collections.
While working on this I tried to improve the tool in a few other ways, too.
=> Allow "Compute an expression on every row" to succeed with empty input

.tt_skip, tools/sam_bitwise_flag_filter/sam_bitwise_flag_filter.py, tools/sam_bitwise_flag_filter/sam_bitwise_flag_filter.xml
This MR should fix this issue:
```
File "/shared/ifbstor1/galaxy/shed_tools/toolshed.g2.bx.psu.edu/repos/devteam/sam_bitwise_flag_filter/0b2424a404d9/sam_bitwise_flag_filter/sam_bitwise_flag_filter.py", line 111
infile = open ( options.input_sam, 'r')
^
TabError: inconsistent use of tabs and spaces in indentation
```
=> sam_bitwise_flag_filter - fix indent

tools/histogram/.shed.yml, tools/histogram/histogram2.xml
The histogram plotting tool doesn't use the header to display the column selection, which is quite inconvenient.
In case there is no header, I think this should still work? Or should we add a boolean to check whether the file has a header?
=> Add "use_header_names" option to histogram
